const
  CLASS_AEROFLOW = 'Aeroflow'
, CLASS_ARRAY = 'Array'
, CLASS_DATE = 'Date'
, CLASS_ERROR = 'Error'
, CLASS_FUNCTION = 'Function'
, CLASS_NUMBER = 'Number'
, CLASS_PROMISE = 'Promise'
, CLASS_REG_EXP = 'RegExp';

export { CLASS_AEROFLOW, CLASS_ARRAY, CLASS_DATE, CLASS_ERROR, CLASS_FUNCTION, CLASS_NUMBER, CLASS_PROMISE, CLASS_REG_EXP };
